version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  commit-message:
    prefix: "chore(gha):"
  groups:
    github-actions:
      patterns:
        - "*"
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: "weekly"
  commit-message:
    prefix: "chore(npm):"
  groups:
    semantic-release:
      patterns:
        - "semantic-release*"
